In [31]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import math

In [32]:
df = pd.read_csv('home.csv')
df

area  bedroom  age   price
0    2600      3.0   20  550000
1    3000      4.0   15  565000
2    3200      NaN   18  610000
3    3600      3.0   30  595000
4    4000      5.0    8  760000
5    4500      5.0   10   25520
6  125545     10.0    4  685421

In [33]:
df = pd.read_csv('home.csv')
df.bedroom = df.bedroom.fillna(math.floor(df.bedroom.median())) # fill NaN data with mean of number of bedroom
df

area  bedroom  age   price
0    2600      3.0   20  550000
1    3000      4.0   15  565000
2    3200      4.0   18  610000
3    3600      3.0   30  595000
4    4000      5.0    8  760000
5    4500      5.0   10   25520
6  125545     10.0    4  685421

In [34]:
# equation of multiple linear regression is,[ y=m1*x1 + m2*x2 + m3*x3 + ...Mn*Xn + c ]

reg = linear_model.LinearRegression() #creat object, load  regression module for calculation
reg.fit(df[['area','bedroom','age']],df.price) # training data, here [ area = x1, bedroom = x2, age = x3 ] and price = y

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
reg.coef_   # printint value of m1,m2,m3, (where m1,m2,m3 is slop)

array([ 8.47135386e+00, -1.63783718e+05, -8.93224743e+03])

In [36]:
reg.intercept_ # printing value of c, where c is intercept point,

1293840.8515536254

In [37]:
reg.predict(df[['area','bedroom','age']]) # prediction of data

array([645870.27033933, 530136.33153552, 505033.86000368, 565019.14985158,
       437349.69991335, 423720.88197234, 683810.8063842 ])

In [38]:
y_pred = reg.predict([[5000,5,10]]) # prediction of data
y_pred

# we can also predict price by using above formula with the help of value of m1,m2,m3 and c
# [ y=m1*x1 + m2*x2 + m3*x3 + ...Mn*Xn + c ] formula

array([427956.5588999])

In [ ]:
#continuos prediction of price:
print('_____________________________________________________')
while True:
    area = float(input("enter area of plot >> "))
    bedroom = float(input("enter number of bedroom >> "))
    age = float(input("enter age of plot >> "))
    price = reg.predict([[area,bedroom,age]])
    if price <0:
        print("enter vailed data")
    elif price>0:
        print("price of this plot is {}".format(price[[0]]))
    if input("you want to continue [Y/N]? ") == "n":
        break
    print('_____________________________________________________')

_____________________________________________________
enter area of plot >> 1254
enter number of bedroom >> 1
enter age of plot >> 2
price of this plot is [1122815.71690208]
you want to continue [Y/N]? y
_____________________________________________________
enter area of plot >> 5632
enter number of bedroom >> 2
enter age of plot >> 2
price of this plot is [996119.58656249]
you want to continue [Y/N]? y
_____________________________________________________
enter area of plot >> 12
enter number of bedroom >> 125
enter age of plot >> 321
enter vailed data
